development:
  app_id: Rjgh9eJVRHDLbD4zVAWECXsoF
  secret: CASoUOkQ3xMuIw0lLG9jTNIJGcBYDp3WUDF9TT6zgRNKTjEG3O
production:
  app_id: Rjgh9eJVRHDLbD4zVAWECXsoF
  secret: CASoUOkQ3xMuIw0lLG9jTNIJGcBYDp3WUDF9TT6zgRNKTjEG3O
